### ISSUE TITLE
can help? could not play RTSP by  H264-RTSP-Server-iOS

### ISSUE THREAD

**Issue by cherishloveyou** [irons163/IRIPCamera#2]
build success, butcould not run demo play rtsp stream by H264-RTSP-Server-iOS

**Comment by irons163** [comment]
Could you build demo? Try build demo on real device instead of simulators.

**Comment by cherishloveyou** [comment]
> Could you build demo? Try build demo on real device instead of simulators.

yes.I build demo success, play .mp4 file is OK
but rtsp stream could not  play stream. H264-RTSP-Server-iOS works well on iPad, and Test it by my mac's VCL
print "player did error : Error Domain=ffmpeg code : -2, ffmpeg msg : No such file or directory Code=1 "(null)"

**Comment by cherishloveyou** [comment]
both  H264-RTSP-Server-iOS and IRIPCamera project should open "Local Networking" when it run. 
Some device lose this options by system when build app, so it  connection  failed!
